### ISSUE TITLE
No such file or directory: '/srv/modoboa/instance/media/webmail'

### ISSUE THREAD

**Issue by jsphpl** [modoboa/modoboa-installer#10]
The error didn't occur yesterday when i tried to run the setup under the exact same conditions (fresh 14.04 DO droplet), so i thought i'd report it.

~~Workaround was to manually create the folder ```/srv/modoboa/instance/media/``` and re-run the setup.~~ Setup runs fine then, but doesn't result in a working modoboa, real workaround: remove `modoboa-stats` and `modoboa-webmail` from `installer.cfg`.
```
…
Starting...
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```

**Comment by jdbaldry** [comment]
I have experienced the same issue and was about to post this. I have experienced this on the 14.04 x64 droplet but not on the 14.04 x32 droplet. Is that the same for you?

**Comment by jsphpl** [comment]
Can't tell for sure but it's highly unlikely that i used a x32 droplet yesterday…

**Comment by tonioo** [comment]
Can you do the following please :
* Remove the /srv/modoboa/instance directory
* Run the installer using the --debug option
* Paste the result here

Thanks.

**Comment by jsphpl** [comment]
```
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInituuislV.c -o tmp/xmlXPathInituuislV.o
    cc tmp/xmlXPathInituuislV.o -lxml2 -o a.out
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    
    ----------------------------------------
Command "/srv/modoboa/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-J8s4wP/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8kgQ5B-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-J8s4wP/lxml
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 7, in <module>
    handle_command_line()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 95, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 36, in run
    self.handle(args)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 219, in handle
    extra_settings = self.install_extensions(extensions)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 168, in install_extensions
    module = __import__(extension[1], locals(), globals(), [])
ImportError: No module named modoboa_stats
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```

**Comment by jsphpl** [comment]
a few lines above it says `Using cached modoboa-stats-1.0.2.tar.gz`- if that helps

**Comment by jsphpl** [comment]
After removing modoboa_stats from `installer.cfg`, got an `ImportError: No module named modoboa_webmail`, so removed that plugin as well. Now installer runs without errors and i can acces the web interface.

**Comment by tonioo** [comment]
Ok, I guess you run on a virtual machine. The log says you don't have enough RAM to compile the lxml dependency.
Increase the amount of RAM allocated to your VM and it should work as expected.

**Comment by jdbaldry** [comment]
Yeah seems to be a RAM issue, I tested with 14.04 x32 and ran in the same problem so it definitely isn't architecture. Is there a recommended amount of RAM to be allocated?

**Comment by jsphpl** [comment]
Thank you, this seems to be the answer. Are there binary packages available? I think you should add a note on the hardware requirements, probably with the installation guides on readthedocs.
