### ISSUE TITLE
CentOS 7 Install Issues

### ISSUE THREAD

**Issue by philip-ulrich** [modoboa/modoboa-installer#120]
# Impacted versions

* Modoboa: Unsure. Latest from git as of today
* Distribution: CentOS
* Codename: Centos 7
* Arch: 64 Bits
* Webserver: Nginx

# Steps to reproduce
Run update
Clone repo
Run install as documented

# Current behavior
First time fails with: 

Traceback (most recent call last):
  File "./run.py", line 76, in <module>
    main()
  File "./run.py", line 67, in main
    scripts.install("nginx", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 147, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 60, in post_run
    self._setup_config("modoboa")
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 53, in _setup_config
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 127, in copy_from_template
    with open(dest, "w") as fp:
IOError: [Errno 2] No such file or directory: '/etc/nginx/conf.d/mail.z3r0.tech.conf'

Second and subsequent fails with: 

Traceback (most recent call last):
  File "./run.py", line 76, in <module>
    main()
  File "./run.py", line 69, in main
    scripts.install("dovecot", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 146, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 128, in install_config_files
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 127, in copy_from_template
    with open(dest, "w") as fp:
IOError: [Errno 2] No such file or directory: '/etc/dovecot/dovecot.conf'

# Expected behavior
To install successfully...

**Comment by tonioo** [comment]
@philip-ulrich Can you please retry using the --debug option?

**Comment by philip-ulrich** [comment]
For some reason it worked this time. Same steps.. Output here: https://pastebin.com/tTidFwM6

**Comment by tonioo** [comment]
I made some tests on CentOS 7.3 and I did not encounter your issue. I close the issue for now, feel free to reopen it if needed.
