### ISSUE TITLE
Install fails on fresh ubuntu 14.04 server install

### ISSUE THREAD

**Issue by T-Grave** [modoboa/modoboa-installer#13]
I get the following error when running the install script "sudo ./run.py mail.domain.com"

```
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 113, in post_run
    self._deploy_instance()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 73, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/robin/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa
```

**Comment by T-Grave** [comment]
Created the folder manually and now I get the following similar error on a different folder;

```
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
    self.apply_settings()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 92, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/robin/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

```

**Comment by T-Grave** [comment]
Created that folder manually too and now it progressed up until "Installing dovecot", but it throws another error at me;
```
File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 57, in main
    scripts.install("dovecot", config)
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/base.py", line 137, in run
    self.install_config_files()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/base.py", line 121, in install_config_files
    utils.copy_from_template(src, dst, context)
  File "/home/robin/modoboa-installer/modoboa_installer/utils.py", line 141, in copy_from_template
    with open(template) as fp:
IOError: [Errno 2] No such file or directory: '/home/robin/modoboa-installer/modoboa_installer/scripts/files/dovecot/20-lmtp.conf.tpl'
```

**Comment by T-Grave** [comment]
It looks like it's searching for the file at;
```
modoboa_installer/scripts/files/dovecot/20-lmtp.conf.tpl
```
while it can actually be found at;
```
modoboa_installer/scripts/files/dovecot/conf.d/20-lmtp.conf.tpl
```

**Comment by tonioo** [comment]
Indeed. Could try using the --debug option ?

**Comment by tonioo** [comment]
And please remove the folders you created by hand.

**Comment by T-Grave** [comment]
Alright, I removed the entire /src/modoboa folder (as it should get created by the installer right?), then ran the script again using the --debug option and it gave me the same error as the first one I posted and right before that error it shows the following;

```
sudo: unable to change directory to /srv/modoboa: No such file or directory
sudo: unable to change directory to /srv/modoboa: No such file or directory
sudo: unable to change directory to /srv/modoboa: No such file or directory
```


Is it skipping folder creation for some reason? For those lines is just apt-get install stuff, nothing out of the ordinary on that end.

**Comment by tonioo** [comment]
I need the full trace in order to help you...

**Comment by T-Grave** [comment]
```Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 113, in post_run
    self._deploy_instance()
  File "/home/robin/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 73, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/home/robin/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa
```

Isn't this a full trace?

**Comment by tonioo** [comment]
Could you try again with the fix I just pushed ?

**Comment by T-Grave** [comment]
Looks like after your patch all is working fine now!


Thanks for the very quick responses and fixes :+1:
