### ISSUE TITLE
Multiple Errors in Installer?

### ISSUE THREAD

**Issue by aspatric** [modoboa/modoboa-installer#160]
# Impacted versions

* Distribution: Ubuntu
* Codename: 16.04 LTS
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
**Error 1**
Installer generates the installer.cfg which contains a misspelled word causing an error later on:
...
[modoboa]
...
devmod = false (instead of devmod**e** = false)
...

**Error 2**
Starting a fresh installation (with installer.cfg provided), all goes well up to _Installing modoboa_. The script claims that the directory /srv/modoboa/instance already exists (although it was a clean install and there was no /srv/modoboa directory prior to installation). Confirming with Yes deletes the directory and the installation stops. Selecting No leads to error 3.

# Full trace using --debug option or current behaviour
**Error 1**
```
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
Traceback (most recent call last):
  File "./run.py", line 97, in <module>
    main(sys.argv[1:])
  File "./run.py", line 84, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 45, in __init__
    self.devmode = config.getboolean("modoboa", "devmode")
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'devmode' in section: 'modoboa'
```

**Error 2**
```
Starting...
Generating new self-signed certificate
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing modoboa
Target directory for Modoboa deployment (/srv/modoboa/instance) already exists. If you choose to continue, it will be removed.
Do you confirm? (Y/n)
```

**Error 3**
```
Do you confirm? (Y/n) n
Traceback (most recent call last):
  File "./run.py", line 97, in <module>
    main(sys.argv[1:])
  File "./run.py", line 84, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 147, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 224, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 185, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 86, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/env/media/webmail'
```

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@aspatric Looks like the new interactive mode introduced some issues. They should be fixed now but before making any new try, please make sure to remove the ``installer.cfg`` file.

**Comment by aspatric** [comment]
Works perfect now. Thanks for quickly fixing the bug!

**Comment by kerk1v** [comment]
Thanks. Had the same issue, thanks a lot for the quick fix.
