### ISSUE TITLE
Postwhite not sufficiently set up

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-installer#182]
#109 introduced postwhite to the installer system, but not to `installer.example.cfg`

Unfortunately, since no migration or upgrade instructions exist #39, it may have been overlooked that `postwhite` also needs to be set up.

```
Installing postwhite
Traceback (most recent call last):
  File "./run.py", line 107, in <module>
    main(sys.argv[1:])
  File "./run.py", line 98, in main
    scripts.install("postfix", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 147, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/postfix.py", line 98, in post_run
    install("postwhite", self.config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 146, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 118, in install_config_files
    context = self.get_template_context()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 88, in get_template_context
    for option, value in self.config.items(self.appname):
  File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'postwhite'
```

Learning from https://github.com/modoboa/modoboa-installer/blob/0ceea13d4b10b83a7db9d1d66849b9805eee98f5/modoboa_installer/config_dict_template.py#L319-L330 allowed to write a valid configuration to be added:

```
# tail -n 3 installer.cfg
[postwhite]
enabled = true
config_dir = /etc
```

**Comment by tonioo** [comment]
@almereyda Indeed, it will fail if you use an existing configuration file. What do you propose in order to fix this?

**Comment by almereyda** [comment]
We have never experienced the new automatic generation of an `installer.cfg` during the installation procedure, as introduced with https://github.com/modoboa/modoboa-installer/blame/master/README.rst#L32-L34

In aligning for more automatised #39, could the installer parse an existing configuration file and warn about deprecated or changed settings?

This could also be useful for customised configuration files as `main.cf` https://github.com/modoboa/modoboa-installer/issues/183#issuecomment-368230506 or in `crontabs` https://github.com/modoboa/modoboa-installer/issues/185#issuecomment-369378175, which get overwritten upon reinstallation.
