### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by karson** [modoboa/modoboa-installer#186]
It throw an error during installation and does not run the webmail server

# Impacted versions 

* Distribution: Ubuntu
* Codename: Xenial Xerus / 64 Bits
* Database: PostgreSQL

# Steps to reproduce
sudo apt-get install python-virtualenv python-pip
git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer
sudo ./run.py < domain>

# Full trace using --debug option or current behaviour
  Error [Errno 12] Cannot allocate memory while executing command python setup.py egg_info
Exception:
Traceback (most recent call last):
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 667, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
bash: modoboa-admin.py: command not found
None

# Expected behavior
Finish installation without  error
# Screenshot link 
https://imgur.com/a/E6ABm

**Comment by tonioo** [comment]
As the error says : " OSError: [Errno 12] Cannot allocate memory". Looks like you're running the installer on a system with not enough RAM.
I want to run modoboa with amavis and clamav, your server neads at least 1GB.

**Comment by karson** [comment]
yes but the server  already has 1GB of ram and 1GB of swap. I will try with more ram.

**Comment by tonioo** [comment]
Is there anything else running on this server?

**Comment by karson** [comment]
no , is fresh installed vps on DO
