### ISSUE TITLE
Installer exits with KeyError: 'pip._vendor.urllib3.contrib'

### ISSUE THREAD

**Issue by rstein** [modoboa/modoboa-installer#188]
Installer exits with `KeyError: 'pip._vendor.urllib3.contrib'`. Tested on multiple fresh Debian 9 and Ubuntu 16.04 installations. No changes to installer.cfg. Any ideas? Thanks!

# Impacted versions

* Distribution: Debian 9 / Ubuntu 16.04
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
```
# apt-get install python python-pip
# python -V
Python 2.7.13
# ./run.py --debug my.domain
```
# Full trace using --debug option or current behaviour
```
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 9, in <module>
    handle_command_line()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 87, in handle_command_line
    commands = scan_for_commands()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 70, in scan_for_commands
    [smart_str(cmdname)])
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 27, in <module>
    import pip
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
None
```

**Comment by rstein** [comment]
It seems this issue is connected with https://github.com/pypa/pip/issues/5079. Downgrading the system pip installation to version 9.0.1 using `pip install --upgrade pip==9.0.1` does not help in this case, because the bundled pip of the virtualenv is used.

**Comment by LDVSOFT** [comment]
Same here, workaround by @rstein did not help me...

**Comment by thibmo** [comment]
Got the same issue, though the workaround did work for me. (I am ran as root, though.)

**Comment by LDVSOFT** [comment]
@thibmo I tried it in different ways, still fails for me) Maybe I need a clean install then.

**Comment by thibmo** [comment]
Strange...
What I did was:
```
sudo ./run.py --debug domain.tld
# Experience a crash here
cd /srv/modoboa
source env/bin/activate
pip install --upgrade pip==9.0.1
deactivate
sudo ./run.py --debug domain.tld
```

**Comment by tonioo** [comment]
pip 9.0.3 fixed this issue. (https://github.com/pypa/pip/releases/tag/9.0.3)
