### ISSUE TITLE
Error occurred while installing on amazon ec-2 instance. 

### ISSUE THREAD

**Issue by parths049** [modoboa/modoboa-installer#189]
Hello 

I'm following these bellow steps.

```
$ git clone https://github.com/modoboa/modoboa-installer
$ cd modoboa-installer
$ sudo ./run.py <mail server hostname>
```

while I  run this third step **sudo ./run.py <mail server hostname>** I get bellow errror.

```
#$ sudo ./run.py "<Domain Name>"
Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/home/ec2-user/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/ec2-user/modoboa-installer/modoboa_installer/package.py", line 101, in get_backend
    "Sorry, this distribution is not supported yet.")
NotImplementedError: Sorry, this distribution is not supported yet.
```

Please Help.
Thank you

**Comment by tonioo** [comment]
@parths049 As the error message says, the linux distribution you're using is not supported by the installer. You must install Modoboa manually.

**Comment by parths049** [comment]
@tonioo Thank you! now it is resolved.
