### ISSUE TITLE
About reinstall

### ISSUE THREAD

**Issue by kryskool** [modoboa/modoboa-installer#190]
_From @jing95 on January 31, 2018 8:53_

# Impacted versions

* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
1. I removed /srv/modoboa and /opt/modoboa-installer
2. Reinstalled modoboa use the following commands
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>
 
   3.Please see Screenshot
# Current behavior
 Reinstall modoboa  
# Expected behavior
 Successful reinstall and needn't to keep previous configuration,I just want to make it look like a new one, never used.
# Video/Screenshot link (optional)
![reinstall](https://user-images.githubusercontent.com/34827497/35613030-bb429914-06a5-11e8-8c36-772fde35b889.png)

_Copied from original issue: modoboa/modoboa#1379_

**Comment by kryskool** [comment]
_From @jing95 on January 31, 2018 9:2_

Is there something I forget to delete?

**Comment by kryskool** [comment]
_From @tonioo on January 31, 2018 12:51_

@jing95 You removed the home directory of the modoboa user, which is a really bad idea... Try something like this before running the installer again:
```shell
> userdel modoboa
```

**Comment by kryskool** [comment]
_From @jing95 on February 1, 2018 1:55_

@tonioo I ran the command ,it shows that group modoboa not removed because it has other members .So I stop here , and then I’ve restored the srv/modoboa , it looks just like it used to be ,now can you tell me how to reinstall it correctly?
Thanks.

**Comment by kryskool** [comment]
_From @jing95 on February 1, 2018 2:26_

According to this instruction, I backup Settings file, and then removed all modoboa file (but I doubt if I completely removed it),next when I have to reinstall, then appeared the problem mentioned above.
![reinstall2](https://user-images.githubusercontent.com/34827497/35657957-14210824-073a-11e8-8ea6-791117c51e56.png)

**Comment by kryskool** [comment]
_From @tonioo on February 1, 2018 15:40_

@jing95 Just run the installer, it will ask you if you want to overwrite the existing files.

**Comment by kryskool** [comment]
_From @tonioo on February 2, 2018 9:44_

Can you run the installer using the --debug option please?

**Comment by kryskool** [comment]
_From @jing95 on February 2, 2018 10:55_

@tonioo I've tried , but it also failed . As is shown in figure.it removed /srv/modoboa/instance , but did not create a new one.
![ae](https://user-images.githubusercontent.com/34827497/35728971-3a577000-0848-11e8-83f5-67f394119b44.png)
Now, I'm trying to uninstall first , then install again.  So could you tell me how to uninstall modoboa completely?
I'm sorry to trouble you , but It's really annoying...

**Comment by kryskool** [comment]
_From @tonioo on February 2, 2018 11:4_

Do you have more information when you run the installer with the --debug option?

**Comment by kryskool** [comment]
_From @jing95 on February 2, 2018 13:18_

@tonioo No other information

**Comment by kryskool** [comment]
_From @jing95 on February 2, 2018 13:25_

So it looks like I have to uninstall it first , and then maybe the installation will work.

**Comment by kryskool** [comment]
_From @tonioo on February 2, 2018 13:26_

Try to remove user and group before running the installer once again.

**Comment by kryskool** [comment]
_From @jing95 on February 2, 2018 13:31_

Ok,I will try

**Comment by gianks** [comment]
Hi, since the upgrade functionality is not currently working i tried a plain reinstall (without --upgrade) but the problems are persisting. 
Now tried removing /srv/modoboa completely and remove the user and the group. Still not working, see below:
```
Running virtualenv with interpreter /usr/bin/python2
New python executable in /srv/modoboa/env/bin/python2
Also creating executable in /srv/modoboa/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /srv/modoboa/env/bin/python2 - setuptools pkg_resources pip wheel:
  Looking in links: /usr/lib/python3/dist-packages, /usr/share/python-wheels/
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Collecting pkg_resources
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/share/python-wheels/pip-18.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 369, in run
    self._warn_about_conflicts(to_install)
  File "/usr/share/python-wheels/pip-18.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 495, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/usr/share/python-wheels/pip-18.1-py2.py3-none-any.whl/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/usr/share/python-wheels/pip-18.1-py2.py3-none-any.whl/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/srv/modoboa/env/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2700, in requires
    dm = self._dep_map
  File "/srv/modoboa/env/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2964, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/srv/modoboa/env/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2973, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/srv/modoboa/env/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2955, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/srv/modoboa/env/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1863, in get_metadata
    raise KeyError("No metadata except PKG-INFO is available")
KeyError: 'No metadata except PKG-INFO is available'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2379, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 996, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 926, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /srv/modoboa/env/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
-sh: 1: /srv/modoboa/env/bin/pip: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
-sh: 1: /srv/modoboa/env/bin/pip: not found
bash: /srv/modoboa/env/bin/activate: File o directory non esistente
Traceback (most recent call last):
  File "/usr/local/bin/modoboa-admin.py", line 9, in <module>
    handle_command_line()
  File "/usr/local/lib/python2.7/dist-packages/modoboa/core/commands/__init__.py", line 103, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/core/commands/__init__.py", line 43, in run
    self.handle(args)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/core/commands/deploy.py", line 229, in handle
    extra_settings = self.find_extra_settings(extensions)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/core/commands/deploy.py", line 174, in find_extra_settings
    module = __import__(extension[1], locals(), globals(), [])
ImportError: No module named modoboa_amavis

```
