### ISSUE TITLE
Debian 9.4 error

### ISSUE THREAD

**Issue by mikysal78** [modoboa/modoboa-installer#195]
git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer
./run.py my.domain

Traceback (most recent call last):
  File "./run.py", line 108, in <module>
    main(sys.argv[1:])
  File "./run.py", line 94, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 147, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 229, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 211, in apply_settings
    self.config.get("radicale", "config_dir"))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'radicale'

**Comment by tonioo** [comment]
Looks like you're running the installer with an old configuration file... Is it the first time you install modoboa?

**Comment by mikysal78** [comment]
non è la prima volta. Ho provato a fare upgrade ma con errori.
Ho formattato la macchina ma volevo mantenere alcune modifiche della configurazione (mail.domain to mx.domain, let's encrypt, timezone ...).
Adesso ho cancellato il vecchio file, ho fatto generare la nuova configurazione e STOP. Edit config and run ./run.py domain ...
Now is OK!
