### ISSUE TITLE
No module named  No module named modoboa_amavis , and EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by xGruntx** [modoboa/modoboa-installer#212]
# Version
 from git clone https://github.com/modoboa/modoboa-installer

* Distribution:  Ubuntu 18.04
* Arch: 64 Bits
* Database: MySQL

# Steps to reproduce
./run --debug --interactive example.ltd 

# Full trace using --debug option or current behaviour
 ```    
Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vtUtNq/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found


Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vtUtNq/mysqlclient/
 Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 9, in <module>
    handle_command_line()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 103, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 43, in run
    self.handle(args)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 229, in handle
    extra_settings = self.find_extra_settings(extensions)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 174, in find_extra_settings
    module = __import__(extension[1], locals(), globals(), [])
ImportError: No module named modoboa_amavis
None
```

**Comment by tonioo** [comment]
Looks like the installer does not work on Ubuntu 18.04 with mysql as database engine. Need to look into it...

**Comment by niko-lay** [comment]
Look like this #a7373e36 is not fixing an issue. Same error on ubuntu 18.04  with pre-installed mysql 5.7

```
  Using cached https://files.pythonhosted.org/packages/b2/ff/9e1aea5cf59afb8a9cda38d52205386dd6ecde5c33b38be0928e6cbebb22/modoboa_postfix_autoreply-1.5.1-py2.py3-none-a
ny.whl
Collecting modoboa-sievefilters
  Using cached https://files.pythonhosted.org/packages/d6/10/c7bf3b689b1167d85d0cc1e397e20cce13d96f8ee13f7c8c95d467d1876f/modoboa_sievefilters-1.4.2-py2.py3-none-any.whl
Collecting modoboa-stats
  Using cached https://files.pythonhosted.org/packages/16/ba/47f87903e8b05bcb1be6edb09fc3cc58e56bf4d7d207dcd32f8ae089704a/modoboa_stats-1.4.1-py2.py3-none-any.whl
Collecting modoboa-webmail
  Using cached https://files.pythonhosted.org/packages/ab/a3/3460afd29eb709045266582e806306ad37da542b13652348e75da192ab7f/modoboa_webmail-1.5.0-py2.py3-none-any.whl
Collecting modoboa-contacts
  Using cached https://files.pythonhosted.org/packages/98/73/9f6239d87f59e498069f4f20143c83057a1fdabdebfa435eb092a3551999/modoboa_contacts-0.7.3-py2.py3-none-any.whl
Collecting modoboa-radicale
  Using cached https://files.pythonhosted.org/packages/95/1a/017a47a4c1c972067d823caffc547e4f43c24bb8c6f191cd550a7fdc9c70/modoboa_radicale-1.3.6-py2.py3-none-any.whl
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6Xmnew/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-6Xmnew/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-6Xmnew/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6Xmnew/mysqlclient/
Target directory for Modoboa deployment (/srv/modoboa/instance) already exists. If you choose to continue, it will be removed.
Do you confirm? (Y/n) y
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 9, in <module>
    handle_command_line()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 103, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 43, in run
    self.handle(args)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 229, in handle
    extra_settings = self.find_extra_settings(extensions)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 174, in find_extra_settings
    module = __import__(extension[1], locals(), globals(), [])
ImportError: No module named modoboa_amavis
None

```

**Comment by niko-lay** [comment]
but manual installation `apt install libmysqlclient-dev` fixes the issue
