### ISSUE TITLE
Trying to replace nginx with apache on Debian 9, Stretch

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-installer#228]
#apache #configure #error 

# Problem

Trying to use apache2 instead of nginx running into apache configuration issue. Did I forget to install or enable some module or other packed needed to support modoboa with apache?

# Impacted versions

* Distribution: Debian 9
* Codename: Stretch
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce

 * Use automated installer and install modoboa
 * disengage nginx (server nginx stop)
 * add /etc/apache2/sites-available/modoboa.conf (see below)
 * a2ensite modoboa
 * engage apache2 (server apache2 start)
 * open local modoboa website.

# Error related output (and conf)

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

```
```

[Sun Aug 05 11:42:11.136711 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572] mod_wsgi (pid=25905): Target WSGI script '/srv/modoboa/instance/instance/wsgi.py' cannot be loaded as Python module.
[Sun Aug 05 11:42:11.136743 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572] mod_wsgi (pid=25905): Exception occurred processing WSGI script '/srv/modoboa/instance/instance/wsgi.py'.
[Sun Aug 05 11:42:11.136758 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572] Traceback (most recent call last):
[Sun Aug 05 11:42:11.136770 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]   File "/srv/modoboa/instance/instance/wsgi.py", line 16, in <module>
[Sun Aug 05 11:42:11.136806 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]     application = get_wsgi_application()
[Sun Aug 05 11:42:11.136811 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Sun Aug 05 11:42:11.137126 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]     django.setup(set_prefix=False)
[Sun Aug 05 11:42:11.137134 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]   File "/srv/modoboa/env/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
[Sun Aug 05 11:42:11.137325 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sun Aug 05 11:42:11.137335 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]   File "/srv/modoboa/env/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
[Sun Aug 05 11:42:11.137627 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]     self._setup(name)
[Sun Aug 05 11:42:11.137647 2018] [wsgi:error] [pid 25905] [remote 84.82.27.46:57572]   File "/srv/modoboa/env/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup

```

```
<VirtualHost *:443>
  ServerName mail.nerderlands.net
  DocumentRoot /srv/modoboa/instance/

  Alias /media/ /srv/modoboa/instance/media/
  <Directory /srv/modoboa/instance/media>
    Require all granted
  </Directory>

  Alias /sitestatic/ /srv/modoboa/instance/sitestatic/
  <Directory /srv/modoboa/instance/sitestatic>
    Require all granted
  </Directory>

  WSGIScriptAlias / /srv/modoboa/instance/instance/wsgi.py
  WSGIDaemonProcess mail.nerderlands.net python-path=/srv/modoboa:/srv/modoboa/env/lib/python2.7/site-packages
  WSGIProcessGroup mail.nerderlands.net

  # Pass Authorization header to enable API usage:
  WSGIPassAuthorization On
</VirtualHost>

```
# Expected behavior

**Comment by JayBeRayBearGun** [comment]
OK seems I solved it. The python path of the instance was not complete and should read:

`  WSGIDaemonProcess mail.nerderlands.net python-path=/srv/modoboa/instance:/srv/modoboa/env/lib/python2.7/site-packages`
