### ISSUE TITLE
install on fresh debian 8.3

### ISSUE THREAD

**Issue by senthai** [modoboa/modoboa-installer#23]
Hi, 

When I run the installer with --debug option I get these traceback errors:
Anything I can do about that?

> sudo: In Ordner »/srv/modoboa« konnte nicht gewechselt werden: Datei oder Verzeichnis nicht gefunden
sudo: In Ordner »/srv/modoboa« konnte nicht gewechselt werden: Datei oder Verzeichnis nicht gefunden
sudo: In Ordner »/srv/modoboa« konnte nicht gewechselt werden: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/tmp/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 127, in post_run
    self._deploy_instance()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 87, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/tmp/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'

**Comment by tonioo** [comment]
Looks like the creation of the modoboa user failed... Have you modified the config. file ?

**Comment by senthai** [comment]
i did not modify anything for my first attempt ;)

but if i list my users after installation i can see the modoboa user.

**Comment by tonioo** [comment]
Could you provide the complete output please ?
