### ISSUE TITLE
Password escaping

### ISSUE THREAD

**Issue by nickdbush** [modoboa/modoboa-installer#235]
# Impacted versions

* Distribution: Ubuntu
* Codename: 18.04 Bionic Beaver
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
Run the installer, and use passwords with percentage signs

# Full trace using --debug option or current behaviour
```Traceback (most recent call last):
  File "./run.py", line 111, in <module>
    main(sys.argv[1:])
  File "./run.py", line 95, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 41, in __init__
    super(Modoboa, self).__init__(config)
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 26, in __init__
    self.app_config = dict(self.config.items(self.appname))
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%j#cVRI%v@'
```

# Expected behavior
The installer does not crash.

# Video/Screenshot link
![image](https://user-images.githubusercontent.com/10998201/45502690-892c2700-b77c-11e8-9482-e653768a82b2.png)

**Comment by nickdbush** [comment]
Duplicate of #100
