### ISSUE TITLE
crontab errors on fresh install

### ISSUE THREAD

**Issue by vingeni** [modoboa/modoboa-installer#24]
I used the modoba installer yesterday (commit 7eb937aeff2b8431f15af3f8f505739a2bc30916)

I have two files : /var/mail/{vmail,mail} which contains some error logs about crontab

(mail is the hostname of the server)

`From vmail@mail Sun Mar 06 19:56:06 2016
Return-path: <vmail@mail>
Envelope-to: vmail@mail
Delivery-date: Sun, 06 Mar 2016 19:56:06 +0100
Received: from vmail by mail with local (Exim 4.84)
	(envelope-from <vmail@mail>)
	id 1acdqY-0008BE-Gm
	for vmail@mail; Sun, 06 Mar 2016 19:56:06 +0100
From: root@mail (Cron Daemon)
To: vmail@mail
Subject: Cron <vmail@mail>   $PYTHON $INSTANCE/manage.py handle_mailbox_operations
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/srv/vmail>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=vmail>
Message-Id: <E1acdqY-0008BE-Gm@mail>
Date: Sun, 06 Mar 2016 19:56:06 +0100

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/handle_mailbox_operations.py", line 79, in handle
    if parameters.get_admin("HANDLE_MAILBOXES") == 'no':
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 273, in get_admin
    __is_defined(app, "A", name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 221, in __is_defined
    raise NotDefined(app, name)
modoboa.lib.parameters.NotDefined: Application 'admin' and/or parameter 'HANDLE_MAILBOXES' not defined
`
`From root@mail Sun Mar 06 19:56:06 2016
Return-path: <root@mail>
Envelope-to: root@mail
Delivery-date: Sun, 06 Mar 2016 19:56:06 +0100
Received: from root by mail with local (Exim 4.84)
	(envelope-from <root@mail>)
	id 1acdqX-00088O-VN
	for root@mail; Sun, 06 Mar 2016 19:56:06 +0100
From: root@mail (Cron Daemon)
To: root@mail
Subject: Cron <root@mail>    $PYTHON $INSTANCE/manage.py generate_rights
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <E1acdqX-00088O-VN@mail>
Date: Sun, 06 Mar 2016 19:56:05 +0100

Unknown command: 'generate_rights'
Type 'manage.py help' for usage.
`

**Comment by vingeni** [comment]
duplicate of https://github.com/tonioo/modoboa/issues/772
