### ISSUE TITLE
install on fresh ubuntu 14.04 modoloboa password returned by port check

### ISSUE THREAD

**Issue by blendi-93** [modoboa/modoboa-installer#25]
hi, 
fresh ubuntu 14.04 64bit updated.

if i run the setup it stops with:

    Traceback (most recent call last):
      File "/srv/modoboa/env/bin/modoboa-admin.py", line 7, in <module>
        handle_command_line()
      File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 95, in handle_command_line
        commands[args.command](commands, verbose=args.verbose).run(remaining)
      File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/__init__.py", line 36, in run
        self.handle(args)
      File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/commands/deploy.py", line 188, in handle
        info = dj_database_url.config(default=url)
      File "/srv/modoboa/env/local/lib/python2.7/site-packages/dj_database_url.py", line 51, in config
        config = parse(s, engine, conn_max_age)
      File "/srv/modoboa/env/local/lib/python2.7/site-packages/dj_database_url.py", line 98, in parse
        'PORT': url.port or '',
      File "/usr/lib/python2.7/urlparse.py", line 113, in port
        port = int(port, 10)
    ValueError: invalid literal for int() with base 10: 'S1kl7y!jHjbbRbz?'
    Traceback (most recent call last):
      File "./run.py", line 64, in <module>
        main()
      File "./run.py", line 54, in main
        scripts.install("modoboa", config)
      File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
        getattr(script, appname.capitalize())(config).run()
      File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
        self.post_run()
      File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 131, in post_run
        self.apply_settings()
      File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 109, in apply_settings
        utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
      File "/root/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
        os.mkdir(path, mode)
    OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

config is default with changed passwords

   [modoboa]
   user = modoboa
   home_dir = /srv/modoboa
   venv_path = %(home_dir)s/env
   instance_path = %(home_dir)s/instance
   timezone = Europe/Berlin
   dbname = modoboa
   dbuser = modoboa
   dbpassword = "S1kl7y!jHjbbRbz?"
   # Extensions to install (to install all of them, use: all)
   extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats

edit: forgot to mask password in config section so changed mine and updated Traceback .

**Comment by blendi-93** [comment]
after reclone and changing my passwords it worked.
