### ISSUE TITLE
Upgrade mode

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-installer#260]
Make it possible to upgrade an existing installation (previously deployed using the installer).

**Comment by gianks** [comment]
Hi, i tried the upgrade right now but i got the following:

```
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 6, in <module>
    from modoboa.core.commands import handle_command_line
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/__init__.py", line 7, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 74, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
None
```


Can you please check?

You might want to look also here for reference: https://stackoverflow.com/questions/38257738/python-2-7-the-packaging-package-is-required-normally-this-is-bundled-with-th

As suggested there i tried installing setuptools==19.2 but didn't work.
I also upgraded to the latest pyinstaller but nothing changed, can't upgrade.

The installer has been just downloaded from git.
Thanks

**Comment by gianks** [comment]
I did some research and i guess the problem could be coming out virtualenv since it requires to be deleted and rebuild in case of updates (and few days ago debian moved from 9 to 10).
