### ISSUE TITLE
Install failure on debian jessie

### ISSUE THREAD

**Issue by ErwanLeroux** [modoboa/modoboa-installer#28]
Hello, I'm currently trying to install modoboa using the installer, but without success. For clarity, I will make a comment for each problem I encounter, chronologically if possible.

For starter, here is my installer.cfg 

```
[general]
tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem

[database]
# Select database engine : postgres or mysql
engine = postgres
#engine = mysql
host = 127.0.0.1
install = false

[postgres]
user = postgres
password = **

[mysql]
user = 
password = 

[modoboa]
user = modoboa
home_dir = /srv/modoboa
venv_path = %(home_dir)s/env
instance_path = %(home_dir)s/instance
timezone = Europe/Paris
dbname = modoboa
dbuser = modoboa
dbpassword = **
# Extensions to install (to install all of them, use: all)
extensions = all
# Deploy Modoboa and enable development mode
devmode = false

[amavis]
enabled = true
user = amavis
home_dir = /var/lib/amavis
config_dir = /etc/amavis/conf.d
max_servers = 1

dbname = amavis
dbuser = amavis
dbpassword = **

[clamav]
enabled = true
user = clamav

[dovecot]
enabled = true
config_dir = /etc/dovecot
user = vmail
home_dir = /srv/vmail
mailboxes_owner = vmail
# Enable extra procotols (in addition to imap and lmtp)
# Example: pop3
extra_protocols = pop3
# Replace localhost with your domain
postmaster_address = postmaster@elendar.fr

[nginx]
enabled = false
config_dir = /etc/nginx

[razor]
enabled = true
config_dir = /etc/razor

[postfix]
enabled = true
config_dir = /etc/postfix
message_size_limit = 11534336

[spamassassin]
enabled = true
config_dir = /etc/spamassassin

dbname = spamassassin
dbuser = spamassassin
dbpassword = **

[uwsgi]
enabled = true
config_dir = /etc/uwsgi
nb_processes = 2
socket_path = /var/run/uwsgi/app/modoboa_instance/socket
```

**Comment by ErwanLeroux** [comment]
The first problem I encountered was during the build of psycopg2

```
Collecting psycopg2
  Using cached psycopg2-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9cQjik/psycopg2/
bash: modoboa-admin.py : commande introuvable
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/opt/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 139, in post_run
    self.apply_settings()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 117, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/opt/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
    os.mkdir(path, mode)



OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```

I solved this problem by running `apt-get install libpq-dev`

Here is the log file for thoroughness
[modoboa-installer.log.1.txt](https://github.com/modoboa/modoboa-installer/files/200834/modoboa-installer.log.1.txt)

**Comment by ErwanLeroux** [comment]
EDIT : Shouldn't have done so late at night, I misread the documentation, and mounted `/tmp` with `noexec` instead of `exec`

The rest of the post is obsolete, I leave it in the case someone does the same mistake

The second problem I encountered was much complex :
The compiling of the module pycrypto failed :

```
Running setup.py bdist_wheel for pycrypto ... error
  Complete output from command /srv/modoboa/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Gxcf76/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQjttCGpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/Crypto
  copying lib/Crypto/__init__.py -> build/lib.linux-x86_64-2.7/Crypto
  copying lib/Crypto/pct_warnings.py -> build/lib.linux-x86_64-2.7/Crypto
  creating build/lib.linux-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
... more lines with copying something
  copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-x86_64-2.7/Crypto/Signature
  running build_ext
  running build_configure
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... configure: error: in `/tmp/pip-build-Gxcf76/pycrypto':
  configure: error: cannot run C compiled programs.
  If you meant to cross compile, use `--host'.
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Gxcf76/pycrypto/setup.py", line 456, in <module>
      core.setup(**kw)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/srv/modoboa/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Gxcf76/pycrypto/setup.py", line 251, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Gxcf76/pycrypto/setup.py", line 278, in run
      raise RuntimeError("autoconf error")
  RuntimeError: autoconf error

  ----------------------------------------
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
  Running setup.py bdist_wheel for django-versionfield2 ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/27/58/ff/d95926fef8276d1c2e4035165945622e8338703e07237e8183
  Running setup.py bdist_wheel for django-xforwardedfor-middleware ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/69/83/39/26a598bd097c5a14b2a98321423fdb181f9b84ce669bacd16c
  Running setup.py bdist_wheel for django-passwords ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/23/e9/3e/d30b3ea5245311238d2c02052fd6c425c129c44cc88d198f76
  Running setup.py bdist_wheel for rfc6266 ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/e9/d6/f2/2ae5718fd4cbe3a6537ab8f05fbf5aa16e8e34b70872992850
  Running setup.py bdist_wheel for progressbar ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/a2/c1/12/54ae83a20ab24295102edff489e515876ee6cf07d3572dbfd8
  Running setup.py bdist_wheel for LEPL ... done
  Stored in directory: /srv/modoboa/.cache/pip/wheels/53/de/e7/ebdd077a9b8fef1ebb774ab96ae7641ce292c6a5fd31458a91
Successfully built modoboa rrdtool psycopg2 django-reversion dj-database-url django-versionfield2 django-xforwardedfor-middleware django-passwords rfc6266 progressbar LEPL
Failed to build pycrypto
```
Following instructions from this [link](http://stackoverflow.com/questions/24152521/pycrypto-installation-configure-error-cannot-run-c-compiled-programs)
I tried `apt-get install python-dev` but it was already installed
Then I tried `pip install pycrypto` but it failed with the same error
```
  checking whether we are cross compiling... configure: error: in `/tmp/pip-build-RkVs5S/pycrypto':
  configure: error: cannot run C compiled programs.
  If you meant to cross compile, use `--host'.
```

I then found [this](https://bugs.launchpad.net/pycrypto/+bug/1294670) and [this](https://systembash.com/centos-pip-python-install-error/) which says that the `/tmp` partition must be mounted with the `exec` option so I tested that theory and it worked

```
export TMPDIR=/opt/modoboa-installer/tmpdir/
pip install pycrypto
Collecting pycrypto
  Using cached pycrypto-2.6.1.tar.gz
Building wheels for collected packages: pycrypto
  Running setup.py bdist_wheel for pycrypto ... done
  Stored in directory: /root/.cache/pip/wheels/96/b0/e6/03e439d41cb2592b5c4c9c77873761d6cbd417b332076680cd
Successfully built pycrypto
Installing collected packages: pycrypto
Successfully installed pycrypto-2.6.1

#to reset TMPDIR
export TMPDIR=
```
But I'm confused about this, since the readme states clearly that `/tmp` partition must be mounted without the `noexec` option.

**Comment by ErwanLeroux** [comment]
Now I'm stuck with no indication of what is the problem, all I've got is this
```
bash: /srv/modoboa/env/bin/modoboa-admin.py: Permission non accordée
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/opt/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 139, in post_run
    self.apply_settings()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 117, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/opt/modoboa-installer/modoboa_installer/utils.py", line 97, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```
```
ls /srv/modoboa/
env  pdfcredentials  rrdfiles
ls /srv/modoboa/env/bin/modoboa-admin.py
/srv/modoboa/env/bin/modoboa-admin.py
```

Any idea ?

**Comment by ErwanLeroux** [comment]
I tried to start from fresh, so I deleted `/srv/modoboa` and tried again.
It failed, stating `/srv/modoboa` didn't existed

```
python-virtualenv est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 76 non mis à jour.
sudo: impossible de changer le répertoire vers /srv/modoboa: Aucun fichier ou dossier de ce type
sudo: impossible de changer le répertoire vers /srv/modoboa: Aucun fichier ou dossier de ce type
sudo: impossible de changer le répertoire vers /srv/modoboa: Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/opt/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 138, in post_run
    self._deploy_instance()
  File "/opt/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 95, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/opt/modoboa-installer/modoboa_installer/utils.py", line 61, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
```

So I deleted the `modoboa` user and tried again.
The install was successful this time.

So apart my mistake with the `/tmp` partition, I just add to execute apt-get install libpq-dev to make the install run to the end.
I haven't finish the setup of the apache virtual host, so I'm not sure everything work right now, but I will keep you posted.

**Comment by ErwanLeroux** [comment]
I can't create new user.

I've got an error 500 and the console says 
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 jquery.min.js:3:4315
```

The request 
`curl "https://modoboa.elendar.fr/admin/accounts/new/" -H "Host: modoboa.elendar.fr" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0" -H "Accept: */*" -H "Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3" --compressed -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-CSRFToken: 1HGcRfFFONnVlBHDVVhTygmYfGOb5iDC" -H "X-Requested-With: XMLHttpRequest" -H "Referer: https://modoboa.elendar.fr/admin/identities/" -H "Cookie: shaarli=n261atodl5j4tkkb5p0q7fqg83; csrftoken=1HGcRfFFONnVlBHDVVhTygmYfGOb5iDC; sessionid=9vyj1h5q00bqjn8b6fkznyuu8bcdmlno" -H "Connection: keep-alive" -H "Pragma: no-cache" -H "Cache-Control: no-cache" --data "csrfmiddlewaretoken=1HGcRfFFONnVlBHDVVhTygmYfGOb5iDC&role=SimpleUsers&username=toto"%"40elendar.fr&first_name=toto&last_name=toto&password1=**&password2=**&is_active=on&email=toto"%"40elendar.fr&quota_act=on&aliases=&stepid=step2&target=next"`

Is there log somewhere to help me debug ?

**Comment by tonioo** [comment]
Hi,
can you set DEBUG to True inside the settings.py file please? You'll get a more readable error trace.

**Comment by ErwanLeroux** [comment]
I already did that, and all I've got is what I posted.

**Comment by tonioo** [comment]
Could you use a regular browser and a javascript console instead of curl ? You should obtain a more explicit message.

**Comment by ErwanLeroux** [comment]
I used a regular browser, I copy pasted this from Firefox. And I did not
get a proper stack trace.

**Comment by tonioo** [comment]
Just to be sure, have you restarted uwsgi after you changed the setting ?

**Comment by ErwanLeroux** [comment]
I probably did, but I can't remember. So I just did it, but now I have forgotten my user name and password...

**Comment by ErwanLeroux** [comment]
Not sure if related, but I tried to change the password using manage.py changepassword and this is what I've got

```
source /srv/modoboa/env/bin/activate
cd /srv/modoboa/instance/
(env) :/srv/modoboa/instance# python manage.py changepassword
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
(env) :/srv/modoboa/instance# ./manage.py changepassword
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
(env) :/srv/modoboa/instance# ls
instance  manage.py  media  postfix_maps  sitestatic
```

**Comment by tonioo** [comment]
@ErwanLeroux Any news about this ?

**Comment by ErwanLeroux** [comment]
No sorry, I gave up the installation. You can close the ticket if you want.
