### ISSUE TITLE
Multiple issues with the installer

### ISSUE THREAD

**Issue by rkyoku** [modoboa/modoboa-installer#291]
# Impacted versions

* Distribution: Ubuntu 18.04
* Arch: 64 Bits
* Database: MariaDB

I already have NextCloud installed on this VM, with nginx / php7.3 / mariadb / redis.

# Steps to reproduce
Run the installer

# Full trace using --debug option or current behaviour
Full trace may be too much. However, here are some info that may help you improve the docs:

Had to run `sudo apt install zlib1g-dev` for pillow to work

Had to run `sudo apt install libmariadbclient-dev-compat` to get mysql_config

Also had to run `curl https://bootstrap.pypa.io/get-pip.py | python3` to get latest working pip.

Also had to create a `sites-available` directory in my (already existing) nginx dir (because now nginx uses only the `conf.d` directory... maybe a solution could be to first try to see which directory exists, and use this one?)

And some other errors I could not fix:

LetsEncrypt:
```
Problem binding to port 80: Could not bind to IPv4 or IPv6.
Can't open /etc/letsencrypt/renewal/mail.mysupakewldomain.conf: No such file or directory.
```

Why does it need to bind to port 80? I already have nginx listening on port 80. When I setup my letsencrypt certificate for NextCloud, I don't have this error.

I created a user named 'local' with full rights (and flushed privileges + updated installer config), but I got plenty of mysql errors. However I can successfully login to mysql manually with this user, and also the databases seem to be created but **they are empty**. I don't know what I did wrong.

```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| amavis             |
| information_schema |
| modoboa            |
| mysql              |
| nextcloud          |
| performance_schema |
| spamassassin       |
+--------------------+
7 rows in set (0.000 sec)

MariaDB [(none)]> use spamassassin ;
Database changed
MariaDB [spamassassin]> show tables;
Empty set (0.000 sec)
```

Amavis:
```
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavis'@'localhost'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'amavis'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'amavis'
ERROR 1044 (42000): Access denied for user 'amavis'@'localhost' to database 'amavis'
```

SpamAssassin (same thing):
```
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'spamassassin'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'spamassassin'@'localhost'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'spamassassin'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'spamassassin'
ERROR 1044 (42000): Access denied for user 'spamassassin'@'localhost' to database 'spamassassin'
```

Plus this specific error that I could not fix:
```
2020-01-08 00:14:54,179 (3658) CRITICAL Unknown command: discover
```

Modoboa (same thing):
```
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'%'
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'localhost'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'modoboa'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'modoboa'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'amavis'
ERROR 1044 (42000) at line 1: Access denied for user 'local'@'localhost' to database 'amavis'
```

Later on:
```
Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/srv/modoboa/env/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/srv/modoboa/env/lib/python3.6/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'modoboa'@'localhost' to database 'modoboa'")

(... and many more exception-lines)
```

nginx:
```
Traceback (most recent call last):
  File "./run.py", line 136, in <module>
    main(sys.argv[1:])
  File "./run.py", line 124, in main
    scripts.install("nginx", config, args.upgrade)
  File "/home/renain/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config, upgrade).run()
  File "/home/renain/modoboa-installer/modoboa_installer/scripts/base.py", line 155, in run
    self.post_run()
  File "/home/renain/modoboa-installer/modoboa_installer/scripts/nginx.py", line 65, in post_run
    self._setup_config("automx", hostname)
  File "/home/renain/modoboa-installer/modoboa_installer/scripts/nginx.py", line 48, in _setup_config
    os.symlink(dst, link)
OSError: [Errno 2] No such file or directory
```

I think I'll try the "old way", see if I get lucky. Unless you have some magic fixes for these ones? I tried the search function a lot, but did not find anything (or maybe did not look hard enough)

Best,

**Comment by tonioo** [comment]
@rkyoku Actually the installer was designed to run on a fresh system...
