### ISSUE TITLE
Installing postfix fails

### ISSUE THREAD

**Issue by th-schwarz** [modoboa/modoboa-installer#313]
# Impacted versions

* Distribution: Ubuntu
* Codename: Focal Fossa
* Arch: 64 Bits
* Database: MySQL

pip --version
pip 20.1 from /env2/lib/python2.7/site-packages/pip (python 2.7)

I'm already on python2, because with python3 I get a lot of other errors.

# Full trace using --debug option or current behaviour
Installing postfix
Reading package lists...
Building dependency tree...
Reading state information...
postfix is already the newest version (3.4.10-1ubuntu1).
postfix-mysql is already the newest version (3.4.10-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Traceback (most recent call last):
  File "./run.py", line 136, in <module>
    main(sys.argv[1:])
  File "./run.py", line 126, in main
    scripts.install("postfix", config, args.upgrade)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config, upgrade).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 155, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 135, in install_config_files
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 145, in copy_from_template
    fp.write(ConfigFileTemplate(buf).substitute(context))
  File "/usr/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python2.7/string.py", line 166, in convert
    val = mapping[named]
KeyError: 'tls_key_file'

I left the configuration of postfix untouched!

Is there someone who has an hint for me?

**Comment by tonioo** [comment]
@th-schwarz What type of certifcate did you choose? (self-signed or LE)

**Comment by th-schwarz** [comment]
It was a regular certificate of Digicert Inc. All browses accepted it.
But I've switch to another product and throw the certificate away.
