### ISSUE TITLE
Cannot run 'run.py' on Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by kkliuiev** [modoboa/modoboa-installer#314]
# Impacted versions

* Distribution:Ubuntu
* Codename: Focal
* Arch: 64 Bits
* Database:MySQL

# Steps to reproduce
sudo ./run.py --stop-after-configfile-check 3423324234.com

# Full trace using --debug option or current behaviour
Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/home/ubuntu/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/ubuntu/modoboa-installer/modoboa_installer/package.py", line 93, in get_backend
    distname = utils.dist_name()
  File "/home/ubuntu/modoboa-installer/modoboa_installer/utils.py", line 79, in dist_name
    name, version, _id = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by jsayles** [comment]
As of Python 3.7 platform.linux_distribution() has been deprecated and it was removed in 3.8.  This makes utils.dist_name() break.  The fix is to switch to bistro.linux_distribution()

These folks ran into this as well:  https://github.com/saltstack/salt/issues/37070

**Comment by jsayles** [comment]
I have verified that with this PR you can get through the full install on Ubuntu 20.04 LTS.
