### ISSUE TITLE
Permissions Issue when running installer

### ISSUE THREAD

**Issue by SNThrailkill** [modoboa/modoboa-installer#327]
# Environment Details

* Modoboa 1.14.0
* OS: Ubuntu 18.04
* Database: MySQL

# Steps to Reproduce
Run installer (with and without the --upgrade flag). Seems that there is an issue with permissions when creating folders. This combined with some cleanup seems to delete the instance folder leaving the frontend useless. Attempted to upgrade from 1.14.0 to 1.15.0. Attempted without --upgrade flag but exact same results occurred. Ran all commands as root. Creating the instance folder manually and using chmod 755 on folder did not change results. Any help is appreciated.

# Stacktrace
```
user@server:~/modoboa-installer$ sudo ./run.py --upgrade mail.domain.com --debug
Welcome to Modoboa installer!

Your mail server is about to be upgraded and the following components will be impacted:
modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 255 kB in 1s (313 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.21p2-3ubuntu1.2).
wget is already the newest version (1.19.4-1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Installing amavis
Reading package lists...
Building dependency tree...
Reading state information...
libdbi-perl is already the newest version (1.640-1).
arc is already the newest version (5.21q-5).
arj is already the newest version (3.10.22-17).
cabextract is already the newest version (1.6-1.1).
libdbd-mysql-perl is already the newest version (4.046-1).
liblz4-tool is already the newest version (0.0~r131-2ubuntu3).
lrzip is already the newest version (0.631-1).
lzop is already the newest version (1.03-4).
p7zip-full is already the newest version (16.02+dfsg-6).
rpm2cpio is already the newest version (4.14.1+dfsg1-2).
unrar-free is already the newest version (1:0.0.1+cvs20140707-4).
amavisd-new is already the newest version (1:2.11.0-1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Installing spamassassin
Reading package lists...
Building dependency tree...
Reading state information...
pyzor is already the newest version (1:1.0.0-3).
spamassassin is already the newest version (3.4.2-0ubuntu0.18.04.4).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
2020-06-07 06:07:28,346 (13999) CRITICAL Unknown command: discover
Installing razor
Reading package lists...
Building dependency tree...
Reading state information...
razor is already the newest version (1:2.85-4.2build3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Can't locate Razor2/Client/Agent.pm:   lib/Razor2/Client/Agent.pm: Permission denied at /usr/bin/razor-admin line 15.
BEGIN failed--compilation aborted at /usr/bin/razor-admin line 15.
Can't locate Razor2/Client/Agent.pm:   lib/Razor2/Client/Agent.pm: Permission denied at /usr/bin/razor-admin line 15.
BEGIN failed--compilation aborted at /usr/bin/razor-admin line 15.
Installing clamav
Reading package lists...
Building dependency tree...
Reading state information...
clamav-daemon is already the newest version (0.102.3+dfsg-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Sun Jun  7 06:07:31 2020 -> ClamAV update process started at Sun Jun  7 06:07:31 2020
Sun Jun  7 06:07:31 2020 -> daily.cld database is up to date (version: 25835, sigs: 2598904, f-level: 63, builder: raynman)
Sun Jun  7 06:07:31 2020 -> main.cvd database is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Sun Jun  7 06:07:31 2020 -> bytecode.cvd database is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Synchronizing state of clamav-daemon.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clamav-daemon
Failed to enable unit: File clamav-daemon.service: Invalid argument
● clamav-daemon.service
   Loaded: loaded (/etc/systemd/system/clamav-daemon.service; bad; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Sun 2020-06-07 06:03:43 UTC; 3min 48s ago
 Main PID: 12805 (clamd)
    Tasks: 2 (limit: 4695)
   CGroup: /system.slice/clamav-daemon.service
           └─12805 /usr/sbin/clamd --foreground=true

Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:6: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:14: Failed to parse service restart specifier, ignoring: Always
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:1: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:2: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:3: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:5: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:6: Assignment outside of section. Ignoring.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:14: Failed to parse service restart specifier, ignoring: Always
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:1: Missing '='.
Jun 07 06:07:32 mail.domain.com systemd[1]: /etc/systemd/system/clamav-daemon.service:1: Missing '='.
amavis.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable amavis
● amavis.service - LSB: Starts amavisd-new mailfilter
   Loaded: loaded (/etc/init.d/amavis; generated)
   Active: active (running) since Sun 2020-06-07 06:03:45 UTC; 3min 48s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 2 (limit: 4695)
   CGroup: /system.slice/amavis.service
           ├─12982 /usr/sbin/amavisd-new (master)
           └─13075 /usr/sbin/amavisd-new (virgin child)

Jun 07 06:03:45 mail.domain.com amavis[12940]: Starting amavisd: amavisd-new.
Jun 07 06:03:45 mail.domain.com systemd[1]: Started LSB: Starts amavisd-new mailfilter.
Jun 07 06:03:45 mail.domain.com amavis[12982]: No $altermime,         not using it
Jun 07 06:03:45 mail.domain.com amavis[12982]: No ext program for   .zoo, tried: zoo
Jun 07 06:03:45 mail.domain.com amavis[12982]: No ext program for   .doc, tried: ripole
Jun 07 06:03:45 mail.domain.com amavis[12982]: No decoder for       .F
Jun 07 06:03:45 mail.domain.com amavis[12982]: No decoder for       .doc
Jun 07 06:03:45 mail.domain.com amavis[12982]: No decoder for       .zoo
Jun 07 06:03:45 mail.domain.com amavis[12982]: Using primary internal av scanner code for ClamAV-clamd
Jun 07 06:03:45 mail.domain.com amavis[12982]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Installing modoboa
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
cron is already the newest version (3.0pl1-128.1ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libjpeg-dev is already the newest version (8c-2ubuntu8).
librrd-dev is already the newest version (1.7.0-1build1).
rrdtool is already the newest version (1.7.0-1build1).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.6).
libxml2-dev is already the newest version (2.9.4+dfsg1-6.1ubuntu1.3).
libxslt1-dev is already the newest version (1.1.29-5ubuntu0.2).
python3-dev is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
Requirement already up-to-date: modoboa in ./env/lib/python3.6/site-packages (1.15.0)
Requirement already satisfied, skipping upgrade: django<2.3,>=2.2 in ./env/lib/python3.6/site-packages (from modoboa) (2.2.13)
Requirement already satisfied, skipping upgrade: Pillow in ./env/lib/python3.6/site-packages (from modoboa) (7.0.0)
Requirement already satisfied, skipping upgrade: oath in ./env/lib/python3.6/site-packages (from modoboa) (1.4.3)
Requirement already satisfied, skipping upgrade: pytz in ./env/lib/python3.6/site-packages (from modoboa) (2019.3)
Requirement already satisfied, skipping upgrade: dnspython==1.16.0 in ./env/lib/python3.6/site-packages (from modoboa) (1.16.0)
Requirement already satisfied, skipping upgrade: feedparser==5.2.1 in ./env/lib/python3.6/site-packages (from modoboa) (5.2.1)
Requirement already satisfied, skipping upgrade: django-xforwardedfor-middleware==2.0 in ./env/lib/python3.6/site-packages (from modoboa) (2.0)
Requirement already satisfied, skipping upgrade: django-reversion==3.0.5 in ./env/lib/python3.6/site-packages (from modoboa) (3.0.5)
Requirement already satisfied, skipping upgrade: gevent==1.4.0 in ./env/lib/python3.6/site-packages (from modoboa) (1.4.0)
Requirement already satisfied, skipping upgrade: lxml in ./env/lib/python3.6/site-packages (from modoboa) (4.5.0)
Requirement already satisfied, skipping upgrade: bcrypt in ./env/lib/python3.6/site-packages (from modoboa) (3.1.4)
Requirement already satisfied, skipping upgrade: cryptography in ./env/lib/python3.6/site-packages (from modoboa) (2.8)
Requirement already satisfied, skipping upgrade: djangorestframework<3.12,>=3.11 in ./env/lib/python3.6/site-packages (from modoboa) (3.11.0)
Requirement already satisfied, skipping upgrade: progressbar33==2.4 in ./env/lib/python3.6/site-packages (from modoboa) (2.4)
Requirement already satisfied, skipping upgrade: jsonfield==2.0.2 in ./env/lib/python3.6/site-packages (from modoboa) (2.0.2)
Requirement already satisfied, skipping upgrade: passlib==1.7.2 in ./env/lib/python3.6/site-packages (from modoboa) (1.7.2)
Requirement already satisfied, skipping upgrade: django-ckeditor==5.8.0 in ./env/lib/python3.6/site-packages (from modoboa) (5.8.0)
Requirement already satisfied, skipping upgrade: ovh in ./env/lib/python3.6/site-packages (from modoboa) (0.5.0)
Requirement already satisfied, skipping upgrade: py-dateutil==2.2 in ./env/lib/python3.6/site-packages (from modoboa) (2.2)
Requirement already satisfied, skipping upgrade: django-braces==1.14.0 in ./env/lib/python3.6/site-packages (from modoboa) (1.14.0)
Requirement already satisfied, skipping upgrade: requests in ./env/lib/python3.6/site-packages (from modoboa) (2.23.0)
Requirement already satisfied, skipping upgrade: django-phonenumber-field[phonenumbers]==4.0.0 in ./env/lib/python3.6/site-packages (from modoboa) (4.0.0)
Requirement already satisfied, skipping upgrade: chardet in ./env/lib/python3.6/site-packages (from modoboa) (3.0.4)
Requirement already satisfied, skipping upgrade: dj-database-url in ./env/lib/python3.6/site-packages (from modoboa) (0.5.0)
Requirement already satisfied, skipping upgrade: uritemplate in ./env/lib/python3.6/site-packages (from modoboa) (3.0.1)
Requirement already satisfied, skipping upgrade: sqlparse in ./env/lib/python3.6/site-packages (from django<2.3,>=2.2->modoboa) (0.3.1)
Requirement already satisfied, skipping upgrade: greenlet>=0.4.14 in ./env/lib/python3.6/site-packages (from gevent==1.4.0->modoboa) (0.4.15)
Requirement already satisfied, skipping upgrade: cffi>=1.1 in ./env/lib/python3.6/site-packages (from bcrypt->modoboa) (1.14.0)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in ./env/lib/python3.6/site-packages (from bcrypt->modoboa) (1.14.0)
Requirement already satisfied, skipping upgrade: django-js-asset>=1.2.2 in ./env/lib/python3.6/site-packages (from django-ckeditor==5.8.0->modoboa) (1.2.2)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in ./env/lib/python3.6/site-packages (from requests->modoboa) (2.9)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.6/site-packages (from requests->modoboa) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./env/lib/python3.6/site-packages (from requests->modoboa) (2019.11.28)
Requirement already satisfied, skipping upgrade: babel in ./env/lib/python3.6/site-packages (from django-phonenumber-field[phonenumbers]==4.0.0->modoboa) (2.8.0)
Requirement already satisfied, skipping upgrade: phonenumbers>=7.0.2; extra == "phonenumbers" in ./env/lib/python3.6/site-packages (from django-phonenumber-field[phonenumbers]==4.0.0->modoboa) (8.12.5)
Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.6/site-packages (from cffi>=1.1->bcrypt->modoboa) (2.19)
Requirement already up-to-date: rrdtool in ./env/lib/python3.6/site-packages (0.1.15)
Requirement already up-to-date: modoboa-amavis in ./env/lib/python3.6/site-packages (1.3.0)
Requirement already up-to-date: modoboa-pdfcredentials in ./env/lib/python3.6/site-packages (1.4.0)
Requirement already up-to-date: modoboa-postfix-autoreply in ./env/lib/python3.6/site-packages (1.6.0)
Requirement already up-to-date: modoboa-sievefilters in ./env/lib/python3.6/site-packages (1.5.0)
Requirement already up-to-date: modoboa-stats in ./env/lib/python3.6/site-packages (1.5.0)
Requirement already up-to-date: modoboa-webmail in ./env/lib/python3.6/site-packages (1.6.0)
Requirement already up-to-date: modoboa-contacts in ./env/lib/python3.6/site-packages (0.8.1)
Requirement already up-to-date: modoboa-radicale in ./env/lib/python3.6/site-packages (1.4.3)
Requirement already up-to-date: mysqlclient in ./env/lib/python3.6/site-packages (1.4.6)
Collecting caldav
  Using cached https://github.com/modoboa/caldav/tarball/master
Requirement already satisfied, skipping upgrade: chardet in ./env/lib/python3.6/site-packages (from modoboa-amavis) (3.0.4)
Requirement already satisfied, skipping upgrade: html2text in ./env/lib/python3.6/site-packages (from modoboa-amavis) (2020.1.16)
Requirement already satisfied, skipping upgrade: idna in ./env/lib/python3.6/site-packages (from modoboa-amavis) (2.9)
Requirement already satisfied, skipping upgrade: modoboa>=1.15.0 in ./env/lib/python3.6/site-packages (from modoboa-amavis) (1.15.0)
Requirement already satisfied, skipping upgrade: reportlab in ./env/lib/python3.6/site-packages (from modoboa-pdfcredentials) (3.5.34)
Requirement already satisfied, skipping upgrade: pytz in ./env/lib/python3.6/site-packages (from modoboa-postfix-autoreply) (2019.3)
Requirement already satisfied, skipping upgrade: django-filter==2.2.0 in ./env/lib/python3.6/site-packages (from modoboa-postfix-autoreply) (2.2.0)
Requirement already satisfied, skipping upgrade: sievelib>=1.1.1 in ./env/lib/python3.6/site-packages (from modoboa-sievefilters) (1.1.1)
Requirement already satisfied, skipping upgrade: lxml in ./env/lib/python3.6/site-packages (from modoboa-stats) (4.5.0)
Requirement already satisfied, skipping upgrade: vobject in ./env/lib/python3.6/site-packages (from modoboa-contacts) (0.9.6.1)
Requirement already satisfied, skipping upgrade: django-webpack-loader in ./env/lib/python3.6/site-packages (from modoboa-contacts) (0.7.0)
Requirement already satisfied, skipping upgrade: drf-nested-routers in ./env/lib/python3.6/site-packages (from modoboa-radicale) (0.91)
Requirement already satisfied, skipping upgrade: icalendar in ./env/lib/python3.6/site-packages (from caldav) (4.0.4)
Requirement already satisfied, skipping upgrade: nose in ./env/lib/python3.6/site-packages (from caldav) (1.3.7)
Requirement already satisfied, skipping upgrade: coverage in ./env/lib/python3.6/site-packages (from caldav) (5.0.3)
Requirement already satisfied, skipping upgrade: requests in ./env/lib/python3.6/site-packages (from caldav) (2.23.0)
Requirement already satisfied, skipping upgrade: six in ./env/lib/python3.6/site-packages (from caldav) (1.14.0)
Requirement already satisfied, skipping upgrade: django-braces==1.14.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (1.14.0)
Requirement already satisfied, skipping upgrade: bcrypt in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (3.1.4)
Requirement already satisfied, skipping upgrade: uritemplate in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (3.0.1)
Requirement already satisfied, skipping upgrade: gevent==1.4.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (1.4.0)
Requirement already satisfied, skipping upgrade: dj-database-url in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (0.5.0)
Requirement already satisfied, skipping upgrade: oath in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (1.4.3)
Requirement already satisfied, skipping upgrade: py-dateutil==2.2 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.2)
Requirement already satisfied, skipping upgrade: django-ckeditor==5.8.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (5.8.0)
Requirement already satisfied, skipping upgrade: jsonfield==2.0.2 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.0.2)
Requirement already satisfied, skipping upgrade: cryptography in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.8)
Requirement already satisfied, skipping upgrade: progressbar33==2.4 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.4)
Requirement already satisfied, skipping upgrade: djangorestframework<3.12,>=3.11 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (3.11.0)
Requirement already satisfied, skipping upgrade: Pillow in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (7.0.0)
Requirement already satisfied, skipping upgrade: django-phonenumber-field[phonenumbers]==4.0.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (4.0.0)
Requirement already satisfied, skipping upgrade: django<2.3,>=2.2 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.2.13)
Requirement already satisfied, skipping upgrade: feedparser==5.2.1 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (5.2.1)
Requirement already satisfied, skipping upgrade: dnspython==1.16.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (1.16.0)
Requirement already satisfied, skipping upgrade: ovh in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (0.5.0)
Requirement already satisfied, skipping upgrade: django-xforwardedfor-middleware==2.0 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (2.0)
Requirement already satisfied, skipping upgrade: passlib==1.7.2 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (1.7.2)
Requirement already satisfied, skipping upgrade: django-reversion==3.0.5 in ./env/lib/python3.6/site-packages (from modoboa>=1.15.0->modoboa-amavis) (3.0.5)
Requirement already satisfied, skipping upgrade: future in ./env/lib/python3.6/site-packages (from sievelib>=1.1.1->modoboa-sievefilters) (0.18.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.4.0 in ./env/lib/python3.6/site-packages (from vobject->modoboa-contacts) (2.8.1)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.6/site-packages (from requests->caldav) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./env/lib/python3.6/site-packages (from requests->caldav) (2019.11.28)
Requirement already satisfied, skipping upgrade: cffi>=1.1 in ./env/lib/python3.6/site-packages (from bcrypt->modoboa>=1.15.0->modoboa-amavis) (1.14.0)
Requirement already satisfied, skipping upgrade: greenlet>=0.4.14 in ./env/lib/python3.6/site-packages (from gevent==1.4.0->modoboa>=1.15.0->modoboa-amavis) (0.4.15)
Requirement already satisfied, skipping upgrade: django-js-asset>=1.2.2 in ./env/lib/python3.6/site-packages (from django-ckeditor==5.8.0->modoboa>=1.15.0->modoboa-amavis) (1.2.2)
Requirement already satisfied, skipping upgrade: babel in ./env/lib/python3.6/site-packages (from django-phonenumber-field[phonenumbers]==4.0.0->modoboa>=1.15.0->modoboa-amavis) (2.8.0)
Requirement already satisfied, skipping upgrade: phonenumbers>=7.0.2; extra == "phonenumbers" in ./env/lib/python3.6/site-packages (from django-phonenumber-field[phonenumbers]==4.0.0->modoboa>=1.15.0->modoboa-amavis) (8.12.5)
Requirement already satisfied, skipping upgrade: sqlparse in ./env/lib/python3.6/site-packages (from django<2.3,>=2.2->modoboa>=1.15.0->modoboa-amavis) (0.3.1)
Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.6/site-packages (from cffi>=1.1->bcrypt->modoboa>=1.15.0->modoboa-amavis) (2.19)
Using legacy setup.py install for caldav, since package 'wheel' is not installed.
ERROR: modoboa-radicale 1.4.3 has requirement caldav==0.6.2, but you'll have caldav 0.5.0 which is incompatible.
ERROR: modoboa-contacts 0.8.1 has requirement caldav==0.6.2, but you'll have caldav 0.5.0 which is incompatible.
Installing collected packages: caldav
  Attempting uninstall: caldav
    Found existing installation: caldav 0.5.0
    Uninstalling caldav-0.5.0:
      Successfully uninstalled caldav-0.5.0
    Running setup.py install for caldav ... done
Successfully installed caldav-0.5.0
Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/templates.py", line 70, in handle
    os.makedirs(top_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/srv/modoboa/instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 6, in <module>
    handle_command_line()
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/core/commands/__init__.py", line 99, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/core/commands/__init__.py", line 39, in run
    self.handle(args)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/core/commands/deploy.py", line 178, in handle
    "startproject", parsed_args.name, verbosity=False
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/commands/startproject.py", line 20, in handle
    super().handle('project', project_name, target, **options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/templates.py", line 74, in handle
    raise CommandError(e)
django.core.management.base.CommandError: [Errno 13] Permission denied: '/srv/modoboa/instance'
None
```

# Expected behavior
Upgrade to proceed. Was attempting to upgrade form 1.14.0 > 1.15.0
# Video/Screenshot link (optional)

![ss](https://user-images.githubusercontent.com/5905096/83961822-9e07f280-a85c-11ea-84d9-977901849404.png)

**Comment by tonioo** [comment]
@SNThrailkill Can you check permissions of the /srv/modoboa/instance folder please?

**Comment by SNThrailkill** [comment]
@tonioo the folder was deleted after running the upgrade. Even manually creating it, chmodding to 755 and rerunning the installer results in the folder being deleted again.

**Comment by SNThrailkill** [comment]
@tonioo any other suggestions?

**Comment by tonioo** [comment]
@SNThrailkill This folder will be destroyed by the installer each time, it's normal. Can you check the permissions of the /srv/modoboa folder? Does it belong to the modoboa user?

**Comment by SNThrailkill** [comment]
@tonioo sure enough that was the issue, I added both the user that starts the services to the modoboa group and made the user/group owner of the folder and the installer worked. After a few more hitches I got it all up and running again. Thank you so much. Closing this Issue.
