### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/etc/cron.d/modoboa' on debian 8

### ISSUE THREAD

**Issue by jakgra** [modoboa/modoboa-installer#34]
Thanks a lot for the great program. When running ./run.py on a fresh debian 8 install I encountered this issue:

ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'modoboa'@'%'
Traceback (most recent call last):
  File "./run.py", line 64, in <module>
    main()
  File "./run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 137, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 121, in install_config_files
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 145, in copy_from_template
    with open(dest, "w") as fp:
IOError: [Errno 2] No such file or directory: '/etc/cron.d/modoboa'
  
  
Steps to reproduce:  
```bash
lxc-create -n mail -t debian
... setup the container networking ...
lxc-console -n mail
... inside the container ...
apt-get update
apt-get install git
git clone https://github.com/modoboa/modoboa-installer
cd modoboa-installer/
apt-get install vim
apt-get install python
./run.py mail.xxx.xxx
... fails ...
./run.py mail.xxx.xxx --debug
... produces the message with the traceback ...
```
  
After I ran `mkdir /etc/cron.d` the ./run.py script successfully finished, so the script should probably check if /etc/cron.d exists and create it if it doesn't ...

**Comment by tonioo** [comment]
Have you checked that a cron daemon is actually installed on your system ? I guess your LXC image is a bit too minimalist...
