### ISSUE TITLE
Debian 11: Not Supported?

### ISSUE THREAD

**Issue by Juliandev02** [modoboa/modoboa-installer#391]
I wanted to install Modoboa on my **Debian 11 Bullseye** server the other day, but it said that my Linux distro is not supported. 
Specifications:
- OS: Debian GNU/Linux 11 (bullseye) x86_64
- Host: PowerEdge R620
- Kernel: 5.4.128-1-pve
- CPU: Intel Xeon E5-2697 v2 (2) @ 3.500GHz
- Memory: 4096MiB

I had installed Modoboa on Debian 10, but after updating to Debian 11 it stopped working. Can someone tell me why Modoboa works on Debian 10 but not on Debian 11?

**Comment by Juliandev02** [comment]
![image](https://user-images.githubusercontent.com/81520713/133885103-6da39e60-e42f-4df6-a822-605330aaaf64.png)
^ Screenshot

**Comment by tonioo** [comment]
@Juliandev02 It should work now.

**Comment by lmfrazao** [comment]
Hello,

on Debian 12 getting this:

Starting...
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing fail2ban
Installing modoboa
Installing automx
Installing radicale

Installing uwsgi
Installing nginx
Traceback (most recent call last):
  File "/root/modoboa-installer/./run.py", line 282, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/./run.py", line 266, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 206, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 85, in post_run
    self._setup_config(
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 43, in _setup_config
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 172, in copy_from_template
    fp.write(ConfigFileTemplate(buf).substitute(context))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/string.py", line 121, in substitute
    return self.pattern.sub(convert, self.template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/string.py", line 114, in convert
    return str(mapping[named])
               ~~~~~~~^^^^^^^
KeyError: 'tls_cert_file'


not compatible with debian 12 or am I doing anything wrong ?

**Comment by lmfrazao** [comment]
same problem on debian 11:

Traceback (most recent call last):
  File "/root/modoboa-installer/./run.py", line 282, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/./run.py", line 266, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 206, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 85, in post_run
    self._setup_config(
  File "/root/modoboa-installer/modoboa_installer/scripts/nginx.py", line 43, in _setup_config
    utils.copy_from_template(src, dst, context)
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 172, in copy_from_template
    fp.write(ConfigFileTemplate(buf).substitute(context))
  File "/usr/lib/python3.9/string.py", line 121, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python3.9/string.py", line 114, in convert
    return str(mapping[named])
KeyError: 'tls_cert_file'

**Comment by lmfrazao** [comment]
well, same error on Debian 10.

I just changed 

[certificate]
generate = false

on installer.cfg
