### ISSUE TITLE
Error when try to install Cerbot

### ISSUE THREAD

**Issue by Mik-Cryo** [modoboa/modoboa-installer#393]
Tryed on Debian 11 & 10.10

```
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Atteint :1 http://security.debian.org/debian-security bullseye-security InRelease
Atteint :2 http://debian.proxad.net/debian bullseye InRelease
Atteint :3 http://debian.proxad.net/debian bullseye-updates InRelease
Lecture des listes de paquets…
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
sudo est déjà la version la plus récente (1.9.5p2-3).
wget est déjà la version la plus récente (1.21-1+b1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
Generating new certificate using letsencrypt
Traceback (most recent call last):
  File "/home/modoboa-installer/./run.py", line 142, in <module>
    main(sys.argv[1:])
  File "/home/modoboa-installer/./run.py", line 123, in main
    ssl_backend.generate_cert()
  File "/home/modoboa-installer/modoboa_installer/ssl.py", line 100, in generate_cert
    self.install_certbot()
  File "/home/modoboa-installer/modoboa_installer/ssl.py", line 77, in install_certbot
    name, version, _id = utils.dist_info()
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by Juliandev02** [comment]
Same Problem here. 
![image](https://user-images.githubusercontent.com/81520713/134377512-54485d95-de70-413c-9021-4a97beb950b0.png)

**Comment by tonioo** [comment]
I've just pushed a fix.
