### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by adivisi** [modoboa/modoboa-installer#452]
Hi I Have the following error when installing:

User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main(sys.argv[1:])
  File "run.py", line 185, in main
    scripts.install("modoboa", config, args.upgrade, args.restore)
  File "/home/user/modoboa-installer/modoboa_installer/scripts/__init__.py", line 23, in install
    getattr(script, appname.capitalize())(config, upgrade, restore).run()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/base.py", line 158, in run
    self.setup_database()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 189, in setup_database
    super(Modoboa, self).setup_database()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/base.py", line 70, in setup_database
    schema = self.get_sql_schema_path()
  File "/home/user/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 201, in get_sql_schema_path
    return super().get_sql_schema_path()()
TypeError: 'NoneType' object is not callable

# Impacted versions

* Distribution: Debian / Ubuntu / Centos
* Codename: Jessie / Trusty / Centos 7 / ...
* Arch: 32 Bits / 64 Bits
* Database: PostgreSQL / MySQL

# Steps to reproduce

# Full trace using --debug option or current behaviour

# Expected behavior

# Video/Screenshot link (optional)

**Comment by pierrbt** [comment]
I got the same error, i think we have to get an older version of the script...
Or maybe someone could just repair it !

**Comment by pierrbt** [comment]
I opened a pull request to fix the bug ( #454 )
