### ISSUE TITLE
os.path.join on dovecot.py(99) getting None type passed from self.restore

### ISSUE THREAD

**Issue by happyjaxx** [modoboa/modoboa-installer#453]
# Impacted versions

* Distribution: Debian
* Codename: Bullseye
* Arch: 64 Bits LXC/Proxmox
* Database: PostgreSQL

# Steps to reproduce

./run.py domainname.fr
First and subsequent launches alike

# Full trace using --debug option or current behaviour

```
...
Reading state information...
dovecot-imapd is already the newest version (1:2.3.13+dfsg1-2+deb11u1).
dovecot-lmtpd is already the newest version (1:2.3.13+dfsg1-2+deb11u1).
dovecot-managesieved is already the newest version (1:2.3.13+dfsg1-2+deb11u1).
dovecot-pgsql is already the newest version (1:2.3.13+dfsg1-2+deb11u1).
dovecot-sieve is already the newest version (1:2.3.13+dfsg1-2+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
User vmail already exists, skipping creation but please make sure the /srv/vmail directory exists.
Traceback (most recent call last):
  File "/root/modoboa-installer/./run.py", line 208, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/./run.py", line 192, in main
    scripts.install("dovecot", config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 23, in install
    getattr(script, appname.capitalize())(config, upgrade, restore).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 160, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/dovecot.py", line 99, in post_run
    mail_dir = os.path.join(self.restore, "mails/")
  File "/usr/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
root@mail:~/modoboa-installer#
```

self.restore is None at that point, which os.path.join doesn't appreciate.

In my case, I'm not restoring, simply commenting out the line is enough to get around it

# Expected behavior

# Video/Screenshot link (optional)

**Comment by pierrbt** [comment]
I got the same error, i think we have to get an older version of the script...
Or maybe someone could just repair it !

**Comment by pierrbt** [comment]
The problem came with PR #424.
I'll try to remove code just to make it work

**Comment by pierrbt** [comment]
I opened a pull request to fix the bug ( #454 )

**Comment by adivisi** [comment]
i have the same issue

**Comment by tonioo** [comment]
Should be fixed now, just update your installer.
