### ISSUE TITLE
KeyError: 'VERSION_ID'

### ISSUE THREAD

**Issue by shamsat** [modoboa/modoboa-installer#468]
I downloaded the latest modoboa-installer , when run the ./run.py 127.0.0.1, get this is error:
`
./run.py --debug  127.0.0.1
Traceback (most recent call last):
  File "/home/user/apps/modoboa-installer/./run.py", line 16, in <module>
    from modoboa_installer import package
  File "/home/user/apps/modoboa-installer/modoboa_installer/package.py", line 121, in <module>
    backend = get_backend()
  File "/home/user/apps/modoboa-installer/modoboa_installer/package.py", line 109, in get_backend
    distname = utils.dist_name()
  File "/home/user/apps/modoboa-installer/modoboa_installer/utils.py", line 101, in dist_name
    return dist_info()[0].lower()
  File "/home/user/apps/modoboa-installer/modoboa_installer/utils.py", line 92, in dist_info
    return info["NAME"], info["VERSION_ID"]
KeyError: 'VERSION_ID'

`

**Comment by Spitfireap** [comment]
Hi, what distro are you using?

**Comment by shamsat** [comment]
I am using the up to date Arch Linux, with the kernel 6.1.4-arch1-1.

**Comment by Spitfireap** [comment]
Sadly we do not support Arch Linux currently. Please use one of the named distro in the README.
