### ISSUE TITLE
Modoboa Upgrading Failed

### ISSUE THREAD

**Issue by pali7x** [modoboa/modoboa-installer#478]
Distribution: Debian 10 x64 
PostgreSQL

Using sudo ./run.py --upgrade domain.com to upgrade failed, and then attempt to reinstalling also fail with the same error message.

fail2ban is already the newest version (0.10.2-2.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 845, in items
    d.update(self._sections[section])
KeyError: 'fail2ban'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 257, in <module>
    main(sys.argv[1:])
  File "./run.py", line 241, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/home/pali7x/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/home/pali7x/modoboa-installer/modoboa_installer/scripts/base.py", line 190, in run
    self.install_config_files()
  File "/home/pali7x/modoboa-installer/modoboa_installer/scripts/base.py", line 146, in install_config_files
    context = self.get_template_context()
  File "/home/pali7x/modoboa-installer/modoboa_installer/scripts/base.py", line 113, in get_template_context
    for option, value in self.config.items(self.appname):
  File "/usr/lib/python3.7/configparser.py", line 848, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'fail2ban'

**Comment by tonioo** [comment]
@pali7x Indeed, that's a use case we don't cover yet. We've added a new feature to the installer which now deploys a fail2ban config. What you can do as a workaround is:
* Backup you existing config file (installer.cfg) and rename it
* Run the installer to generate a new config file (using the --stop-after-configfile-check option)
* Copy the fail2ban section from the new file to the old one
* Restore your original config file
* Run the installer in upgrade mode again

**Comment by pali7x** [comment]
Hi @tonioo, Thanks for your reply. I am already half-way on restoring the server through the latest installation with fail2ban included.

**Comment by FranMercedesG** [comment]
> @pali7x Indeed, that's a use case we don't cover yet. We've added a new feature to the installer which now deploys a fail2ban config. What you can do as a workaround is:
> 
> * Backup you existing config file (installer.cfg) and rename it
> * Run the installer to generate a new config file (using the --stop-after-configfile-check option)
> * Copy the fail2ban section from the new file to the old one
> * Restore your original config file
> * Run the installer in upgrade mode again

I did that, but now, I have the this error:

NOTICE:  view "dkim" does not exist, skipping
DROP VIEW
Traceback (most recent call last):
  File "/root/modoboa-installer/./run.py", line 257, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/./run.py", line 241, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 191, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 283, in post_run
    self._deploy_instance()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 178, in _deploy_instance
    self.dbname, self.dbuser, self.dbpassword,
AttributeError: 'Modoboa' object has no attribute 'dbpassword'

**Comment by Spitfireap** [comment]
> AttributeError: 'Modoboa' object has no attribute 'dbpassword'

You must have a formatting issue on your installer.cfg. You should back it up, regen a clean one and copy the information from the former.
