### ISSUE TITLE
Centos 7 modoboa 2y old - upgrade using script fails at fail2ban

### ISSUE THREAD

**Issue by ionescu77** [modoboa/modoboa-installer#483]
# Impacted versions

* Distribution: Centos
* Codename: Centos 7.9
* Arch: 64 Bits (Digital Ocean)
* Database: PostgreSQL

# Steps to reproduce
- I cloned the latest `modoboa-installer` repo
- copied the `installer.cfg` file (I have made a copy as back-up)
- started the script with upgrade option
- note: I have `fail2ban` installed on my centos 7
- note: I have an old modoboa version c.a 2y (April 2020) I am not sure how to determine the version (I also used installer script)
- note: `python3` is pointing to `python3.6` (centos 7 default), I will try to upgrade it to `python3.9`
- note: backup option of the `run.py` script ran without issues

# Full trace using --debug option or current behaviour
```
[root@hermes01 modoboa-installer]# sudo ./run.py --upgrade my-domain.com
Welcome to Modoboa installer!

Your mail server is about to be upgraded and the following components will be impacted:
modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing fail2ban
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'fail2ban'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 257, in <module>
    main(sys.argv[1:])
  File "./run.py", line 241, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 190, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 146, in install_config_files
    context = self.get_template_context()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 113, in get_template_context
    for option, value in self.config.items(self.appname):
  File "/usr/lib64/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'fail2ban'
```

- I will try to run again with `--debug`
# Expected behavior
I expected the upgrade script to run to the end, maybe provide output on installed vs upgraded version numbers of the modules.

# Video/Screenshot link (optional)

**Comment by ionescu77** [comment]
## Workaround

- comment out following line (or remove)
https://github.com/modoboa/modoboa-installer/blob/06a81c7a80bdf249322fb5f0604c55642a66867c/run.py#L25

- run script with upgrade option
- SUCCESS:
```
Congratulations! You can enjoy Modoboa at https://mail01.my-domain.com
```

## Conclusion
I must have used an older `modoboa-installer` version, which did not include the `fail2ban` setup section.
I installed manually fail2ban and set my own jails for email (I have fail2ban on all my servers)

> I'll try to investigate why the installer could not pick-up on the installed fail2ban version

**Comment by ionescu77** [comment]
## FYI Backup pre-upgrade

<img width="803" alt="Screenshot 2023-02-24 at 15 41 20" src="https://user-images.githubusercontent.com/8016748/221193015-1ccc1419-93bf-455e-a02b-ef9a31e35191.png">

**Comment by ionescu77** [comment]
## Closing notes

I might drop the upgrade thing, things seem to old.

I have checked the virtualenv in `/srv` and it looks like it's python2 😄 😢
