### ISSUE TITLE
Installer fails to unlink file for postwhite

### ISSUE THREAD

**Issue by fbfeix** [modoboa/modoboa-installer#524]
# Impacted versions

* Distribution: Ubuntu
* Codename: Jammy Jellyfish 22.04.3 LTS
* Arch: 64 Bits
* Database: not applicable
* Python 3.10.12

# Steps to reproduce
Just running the installer on a clean install of Ubuntu 22.04.3 with Python 3.10.12 on revision 4a2e9f2. It is not an upgrade but the very first execution of the installer.

# Full trace using --debug option or current behaviour

```
Traceback (most recent call last):
  File "/root/modoboa-installer/run.py", line 282, in <module>
    main(sys.argv[1:])
  File "/root/modoboa-installer/run.py", line 266, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 206, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/postfix.py", line 100, in post_run
    install("postwhite", self.config, self.upgrade, self.archive_path)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 206, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/postwhite.py", line 47, in post_run
    self.install_from_archive(SPF_TOOLS_REPOSITORY, install_dir)
  File "/root/modoboa-installer/modoboa_installer/scripts/postwhite.py", line 41, in install_from_archive
    os.unlink(target)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/master.zip'
```

# Expected behavior
Should install postwhite without problems. Unlinking should be successful on a clean ubuntu.

**Comment by tonioo** [comment]
@fbfeix I see you're working on a fix for that issue. Do you think you could create a PR soon for that?
