### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by koxu1996** [modoboa/modoboa-installer#61]
Hello. I am trying to install modoboa on digitalocean droplet. This is output of sudo ``./run.py site.com --debug``:
```
Welcome to Modoboa installer!
Your mail server wyszukiwarkarozrywki.pl will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) Y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:2 http://mirrors.digitalocean.com/ubuntu xenial InRelease
Get:3 http://mirrors.digitalocean.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:4 http://mirrors.digitalocean.com/ubuntu xenial-backports InRelease
Fetched 190 kB in 0s (469 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.16-0ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Overwrite the existing SSL certificate? (y/N) N
Installing modoboa
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.1ubuntu2).
cron is already the newest version (3.0pl1-128ubuntu2).
libffi-dev is already the newest version (3.2.1-4).
libjpeg-dev is already the newest version (8c-2ubuntu8).
librrd-dev is already the newest version (1.5.5-4).
libxslt1-dev is already the newest version (1.1.28-2.1).
python-dev is already the newest version (2.7.11-1).
rrdtool is already the newest version (1.5.5-4).
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
postgresql is already the newest version (9.5+173).
postgresql-server-dev-all is already the newest version (173).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
0
-sh: 1: /srv/modoboa/env/bin/pip: not found
bash: /srv/modoboa/env/bin/activate: No such file or directory
bash: modoboa-admin.py: command not found
Traceback (most recent call last):
  File "./run.py", line 70, in <module>
    main()
  File "./run.py", line 60, in main
    scripts.install("modoboa", config)
  File "/home/andrew/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/andrew/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/andrew/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 157, in post_run
    self.apply_settings()
  File "/home/andrew/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 132, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/andrew/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

```
I see there is a problem with pip, but it is installed. When I list files in /srv/modoboa/env/bin I get only:
``python  python2  python2.7``. How to fix installation?

**Comment by tonioo** [comment]
Is it a fresh install on a new server/vm ?

**Comment by koxu1996** [comment]
No, I have installed LAMP stack

**Comment by tonioo** [comment]
Can you check that the python-pip package is installed ?

**Comment by koxu1996** [comment]
python-pip is installed by apt

**Comment by tonioo** [comment]
Can you try to remove the virtualenv directory and to restart the installer ?

**Comment by koxu1996** [comment]
I removed modoboa user, /srv/modoboa directory and postrgreSQL database and installation go on with errors in amavis:
```
Oct 16 20:27:43 ubuntu-1024mb-lon1-01 amavis[31340]: (!!)TROUBLE in pre_loop_hook: Timeout::_run: check: no loaded plugin implements 'check_main': cannot scan!\nCheck that the necessary '.pre' files are in th
Oct 16 20:27:43 ubuntu-1024mb-lon1-01 amavis[31340]: (!)_DIE: Suicide () TROUBLE in pre_loop_hook: Timeout::_run: check: no loaded plugin implements 'check_main': cannot scan!\nCheck that the necessary '.pre'
```
and also
```Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
```

**Comment by tonioo** [comment]
Have you checked if those services run after the installation process ?

**Comment by tonioo** [comment]
@koxu1996 ping

**Comment by koxu1996** [comment]
Nginx was running, but I gave up with installing own mail server, because clamav require much CPU speed and my VPS was lagging. Now I am using G Suite, but maybe someday I will switch to better computer and install modoboa.
