### ISSUE TITLE
Error when installing if plugin webmail was disabled

### ISSUE THREAD

**Issue by jaysee** [modoboa/modoboa-installer#62]
Hello and thank you for this nice easy installer, I just noticed a problem when removing the webmail plugin from the list in installer.cfg, I got : 

`
Traceback (most recent call last):
  File "modoboa-installer/run.py", line 70, in <module>
    main()
  File "modoboa-installer/run.py", line 60, in main
    scripts.install("modoboa", config)
  File "/home/src/mailserver/modoboa/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/home/src/mailserver/modoboa/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/home/src/mailserver/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 157, in post_run
    self.apply_settings()
  File "/home/src/mailserver/modoboa/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 132, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/home/src/mailserver/modoboa/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
`
cheers

**Comment by jaysee** [comment]
Seems like a false alert, 

i already had mysql installed and the installer failed to get through a "reinstallation" of mysql, breaking the things...

So I close, thank again for the work!
