### ISSUE TITLE
 OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'

### ISSUE THREAD

**Issue by Nodeswitch** [modoboa/modoboa-installer#69]
When running the automated installer on Debian 8.6, I'm getting the below error.

```
Traceback (most recent call last):
  File "./run.py", line 73, in <module>
    main()
  File "./run.py", line 63, in main
    scripts.install("modoboa", config)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 157, in post_run
    self.apply_settings()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 132, in apply_settings
    utils.mkdir(d, stat.S_IRWXU | stat.S_IRWXG, pw[2], pw[3])
  File "/root/modoboa-installer/modoboa_installer/utils.py", line 79, in mkdir
    os.mkdir(path, mode)
OSError: [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail'
```
```
root@mail:~/modoboa-installer# ls -latr /srv/modoboa/
total 40
-rw-r--r-- 1 modoboa modoboa  675 Nov 12  2014 .profile
-rw-r--r-- 1 modoboa modoboa 3515 Nov 12  2014 .bashrc
-rw-r--r-- 1 modoboa modoboa  220 Nov 12  2014 .bash_logout
-rw-r--r-- 1 modoboa modoboa    0 Oct 19 21:41 .cloud-locale-test.skip
drwxr-xr-x 3 root    root    4096 Nov 14 06:13 ..
drwx------ 3 modoboa modoboa 4096 Nov 14 06:14 .cache
drwxr-xr-x 6 modoboa modoboa 4096 Nov 14 06:16 env
drwxrwx--- 2 modoboa modoboa 4096 Nov 14 06:16 rrdfiles
drwxrwx--- 2 modoboa modoboa 4096 Nov 14 06:16 pdfcredentials
drwxr-xr-x 3 modoboa modoboa 4096 Nov 14 06:33 instance
drwxr-xr-x 7 modoboa modoboa 4096 Nov 14 06:33 .
```
```
root@mail:/srv/modoboa# ls -latr instance/
total 16
-rwxr-xr-x 1 modoboa modoboa  251 Nov 14 06:33 manage.py
drwxr-xr-x 7 modoboa modoboa 4096 Nov 14 06:33 ..
drwxr-xr-x 3 modoboa modoboa 4096 Nov 14 06:33 .
drwxr-xr-x 2 modoboa modoboa 4096 Nov 14 06:33 instance
```

This is a fresh image, nothing else running on it. As above, the modoboa account is created as part of the script and is set up as the owner of /srv/modoboa.

Let me know what I can do to assist.

**Comment by tonioo** [comment]
Hi,
have you tried to run the installer using the --debug option? I think this issue might be the same than #68.

**Comment by tonioo** [comment]
@Nodeswitch ping

**Comment by Nodeswitch** [comment]
Sorry for the delay. Busy couple of weeks.

I've since spun up a new Debian instance and just ran the script there with the debug option, but everything seems to have gone smoothly this time. 

Thanks for the quick response!

**Comment by tonioo** [comment]
Great! So I close the issue.
