### ISSUE TITLE
FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by adeklanin** [modoboa/modoboa-installer#92]
_Copied from issue: [modoboa/modoboa#1005](https://github.com/modoboa/modoboa/issues/1005)_

Hello,

First I'm gonna say thanks @tonioo and all contributors for Modoboa, it helped me move from our old and heavy Zimbra Java based mail server to.. I would say modern, and yet simple Modoboa.

Btw all of mail server terminology are new stuff for me, but I've done my homework, reading, testing configuring, debugging, and so on. So please don't be to harsh on me.

Specs:
- Install using installer
- Debian 8.6 on 4Gb DigitalOcean VM
- PostgreSQL as Database
- most of the extensions, except: Radicale and IMAP Migration

After deploying Modoboa for almost a week, and I'm getting this error:

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 67, in ready
    load_core_settings()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 55, in load_core_settings
    parameters.register(GeneralParametersForm, ugettext_lazy("General"))
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
    form = formclass()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 304, in __init__
    super(GeneralParametersForm, self).__init__(*args, **kwargs)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
    self._load_initial_values()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
    if not db_utils.db_table_exists("lib_parameter"):
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
    return table in connection.introspection.table_names()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    with self.connection.cursor() as cursor:
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

This message actually delivered to the admin account I've setup, to receive error message from the services. So far from what I read, this issue are related to PostgreSQL, and I see on [dovecot-sql-postgres.conf.ext.tpl](https://github.com/modoboa/modoboa-installer/blob/81b32d21ad723a2706e7111378395b164ba91142/modoboa_installer/scripts/files/dovecot/dovecot-sql-postgres.conf.ext.tpl) that we could add to **dovecot-sql-postgres.conf.ext** `maxconns` increase value from default `5` for example to `10` or `20`.

Also theres this value `max_connections` and `superuser_reserved_connections` on **postgresql.conf**, are `max_connections` need to be the same value with `maxconns` from **dovecot-sql-postgres.conf**? Or is there some kind of rule about this value, which one should we tune first or should we do both?

I already doubled both `maxconns` and `max_connections` value from default, need to test when high traffic tomorrow morning. While waiting, are there any suggestion about this issue?

**Comment by tonioo** [comment]
@adeklanin I just pushed a fix, could you try it please?

**Comment by adeklanin** [comment]
Just for update, today after increase `max_connections` from `100` to `200` on **postgresql.conf** and I also revert back `maxconns` to `5` on **dovecot-sql-postgres.conf**, after log message showing it as unknown variable, solved the problem. But I'm not sure changing default PostgreSQL configuration would be good approaches for live server. I think it would be better if fix done on Modoboa (Postfix) side.

**Comment by adeklanin** [comment]
@tonioo the issue appeared on live server. Sorry for the question, but who do I test it on live environment?

**Comment by tonioo** [comment]
You won't see any difference on a test server with no traffic. I just changed postfix's configuration (look at the diff) so maybe you could apply changes manually?

**Comment by adeklanin** [comment]
I'll try to apply it manually, and will update the result tomorrow at about this time. Thanks.

**Comment by adeklanin** [comment]
I guess I need to revert the 'max_connections' value to '100' for testing it right?

**Comment by tonioo** [comment]
yes.

**Comment by tonioo** [comment]
@adeklanin It should be fixed now, there were some mistakes. Is it better now?

**Comment by adeklanin** [comment]
@tonioo to be sure I need to check when high volume traffic on working hour in the morning. But I think last commit a2c46bb fixed this issue. I'll close this for now.

**Comment by adeklanin** [comment]
@tonioo from mail.log
```
Jan 18 17:38:34 mail postfix/submission/smtpd[15140]: warning: Connection concurrency limit exceeded: 51 from unknown[111.44.222.33] for service submission
```
and from Mail Delivery System
```
Transcript of session follows.
 Out: 421 4.7.0 host.domain.tld Error: too many connections from
     111.44.222.33
For other details, see the local mail logfile
```
I'm not sure this are more postfix issue than Modoboa configuration. But I guess I just need to adapt with the traffic load.

Screenshot from Statistics page
https://www.dropbox.com/s/crry63rc4vd399t/Graphical%20statistics.png?dl=0

**Comment by tonioo** [comment]
Sorry but this has nothing to do with the original issue. It looks like one MTA is flooding your server with too many connections (IP `111.44.222.33`) so postfix, which has a default limit of 50 concurrent connections, blocks all the others. I suggest you consult http://www.postfix.org/TUNING_README.html.

**Comment by adeklanin** [comment]
Ok will do. Thanks
